# PostgreSQL
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbkarwas
    username: postgres
    password: root123
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        
server:
  port: 8080
  
#Mysql
# spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dbkarwas?useSSL=false&serverTimezone=UTC
#    username: root
#    password: admin
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect.storage_engine: innodb